DROP PROCEDURE IF EXISTS RCA_DEMO.RCA_TOOLS.DESCRIPTIVE_ANALYTICS(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARIANT);
CALL RCA_DEMO.RCA_TOOLS.SCHEMA_DISCOVERY('RCA_DEMO', 'RCA_TOOLS');
GRANT USAGE ON AGENT RCA_DEMO.RCA_TOOLS.RCA_PRESCRIPTIVE_AGENT TO ROLE PUBLIC;
